Repository naver/egjs-flicking, pull requests merged in 2019-05, with the labels that each got.

#188 fix: remove unsupported method
  src/Flicking.ts
  src/index.ts
Labels: 3.x, bug

#197 fix: interrupting at bounce area
  src/states/AnimatingState.ts
Labels: 3.x, bug

#218 feat: add getLastIndex
  src/Flicking.ts
Labels: 3.x, feature

#207 feat: add react-flicking@3
  packages/react-flicking/LICENSE
  packages/react-flicking/README.md
  packages/react-flicking/package-lock.json
  packages/react-flicking/package.json
  packages/react-flicking/public/favicon.ico
  packages/react-flicking/public/index.html
  packages/react-flicking/public/manifest.json
  packages/react-flicking/rollup.config.js
  packages/react-flicking/src/demo/App.css
  packages/react-flicking/src/demo/App.tsx
  packages/react-flicking/src/demo/Header.tsx
  packages/react-flicking/src/demo/css/align.css
  packages/react-flicking/src/demo/css/bound.css
  packages/react-flicking/src/demo/css/common.css
  packages/react-flicking/src/demo/css/features.css
  packages/react-flicking/src/demo/css/gap.css
  packages/react-flicking/src/demo/css/highlight.css
  packages/react-flicking/src/demo/css/infinite.css
  packages/react-flicking/src/demo/css/parallax.css
  packages/react-flicking/src/demo/css/plugins.css
  packages/react-flicking/src/demo/css/progress.css
  packages/react-flicking/src/demo/css/variable-size.css
  packages/react-flicking/src/demo/features/Align.tsx
  packages/react-flicking/src/demo/features/Bound.tsx
  packages/react-flicking/src/demo/features/FreeScroll.tsx
  packages/react-flicking/src/demo/features/Gap.tsx
  packages/react-flicking/src/demo/features/InfiniteFlicking.tsx
  packages/react-flicking/src/demo/features/PlaceHolderItem.tsx
  packages/react-flicking/src/demo/features/Progress.tsx
  packages/react-flicking/src/demo/features/Snap.tsx
  packages/react-flicking/src/demo/features/VariableSize.tsx
  packages/react-flicking/src/demo/plugins/AutoPlay.tsx
  packages/react-flicking/src/demo/plugins/Fade.tsx
  packages/react-flicking/src/demo/plugins/Parallax.tsx
  packages/react-flicking/src/demo/react-app-env.d.ts
  packages/react-flicking/src/demo/serviceWorker.ts
  packages/react-flicking/src/demo/utils.ts
  packages/react-flicking/src/index.tsx
  packages/react-flicking/src/react-app-env.d.ts
  packages/react-flicking/src/react-flicking/Clone.tsx
  packages/react-flicking/src/react-flicking/Flicking.tsx
  packages/react-flicking/src/react-flicking/consts.ts
  packages/react-flicking/src/react-flicking/index.ts
  packages/react-flicking/src/react-flicking/types.ts
  packages/react-flicking/tsconfig.build.json
  packages/react-flicking/tsconfig.declaration.json
  packages/react-flicking/tsconfig.json
  packages/react-flicking/yarn.lock
Labels: 3.x, React, enhancement, feature

#221 fix: fix bug for node.js
  src/utils.ts
Labels: 3.x, Angular, React, Vue, bug

#223 fix: correct resizing for height-dependent panel
  package-lock.json
  src/components/Viewport.ts
  test/manual/html/resize.html
  test/manual/js/resize.js
Labels: 3.x, bug

#225 fix: every panel to be initialized with CSS "left"
  src/components/Viewport.ts
  test/unit/initialize.spec.ts
Labels: 3.x, bug

#231 fix: fix freeScroll's duration
  src/moves/FreeScroll.ts
Labels: 3.x, bug
