Repository naver/egjs-flicking, pull requests merged in 2019-10, with the labels that each got.

#307 docs: fix mismatched description in jsdoc
  src/Flicking.ts
Labels: :bookmark:3.x, :memo: Docs

#306 feat: collect information with GA
  packages/ngx-flicking/projects/ngx-flicking/src/lib/ngx-flicking.component.ts
  packages/react-flicking/src/react-flicking/Flicking.tsx
  packages/vue-flicking/src/Flicking.ts
  src/Flicking.ts
Labels: :bookmark:3.x, :sparkles:Feature

#304 fix: "select" event on mobile device
  src/states/HoldingState.ts
Labels: :bookmark:3.x, :bug:Bug

#309 update flicking dependencies
  packages/ngx-flicking/projects/ngx-flicking/package.json
  packages/react-flicking/package.json
  packages/vue-flicking/package.json
Labels: :bookmark:3.x, :wrench:Dev-env
