Repository naver/egjs-flicking, pull requests merged in 2019-06, with the labels that each got.

#245 Add `rebuild()` method for panel update.
  package-lock.json
  package.json
  packages/flicking-plugins/dist/OpacityEffect.min.js
  packages/flicking-plugins/dist/ParallaxEffect.min.js
  packages/flicking-plugins/dist/all.js
  packages/flicking-plugins/dist/all.min.js
  packages/flicking-plugins/dist/plugin/OpacityEffect.js
  packages/flicking-plugins/dist/plugin/ParallaxEffect.js
  packages/flicking-plugins/dist/plugins.esm.js
  packages/react-flicking/package-lock.json
  packages/react-flicking/package.json
  packages/react-flicking/src/App.tsx
  packages/react-flicking/src/PanelRebuild.tsx
  packages/react-flicking/src/react-flicking/index.tsx
  src/Flicking.js
  src/flicking.d.ts
  test/unit/methods.spec.js
Labels: 2.x

#249 fix: resize() binding for window resize event
  src/Flicking.ts
Labels: 3.x, bug

#251 fix: current panel can be cloned one
  src/components/Viewport.ts
Labels: 3.x, bug

#255 fix: camera goes too far when bound is enabled
  src/moves/Snap.ts
  test/manual/html/bound.html
  test/manual/js/bound.js
  test/unit/initialize.spec.ts
Labels: 3.x, bug

#254 docs: update links
  README.md
  declaration/Flicking.d.ts
  declaration/components/Panel.d.ts
  declaration/components/PanelManager.d.ts
  declaration/components/StateMachine.d.ts
  declaration/components/Viewport.d.ts
  declaration/consts.d.ts
  declaration/index.d.ts
  declaration/index.umd.d.ts
  declaration/moves/FreeScroll.d.ts
  declaration/moves/MoveType.d.ts
  declaration/moves/Snap.d.ts
  declaration/states/AnimatingState.d.ts
  declaration/states/DisabledState.d.ts
  declaration/states/DraggingState.d.ts
  declaration/states/HoldingState.d.ts
  declaration/states/IdleState.d.ts
  declaration/states/State.d.ts
  declaration/types.d.ts
  declaration/utils.d.ts
  packages/flicking-plugins/README.md
  packages/react-flicking/README.md
Labels: 2.x, doc

#259 feat: add useStatistics option for analytics
  src/Flicking.ts
  src/consts.ts
  src/ga/ga.ts
  src/types.ts
  src/utils.ts
  test/unit/assets/utils.ts
  test/unit/initialize.spec.ts
Labels: :bookmark:3.x, :rocket:Enhancement, :sparkles:Feature

#262 fix: resize is regarded as member variable not method
  src/Flicking.ts
  src/types.ts
Labels: :bookmark:3.x, :bug:Bug, :memo: Docs

#263 docs: collectStatistics on README
  README.md
  README_KR.md
  packages/ngx-flicking/README.md
  packages/ngx-flicking/projects/ngx-flicking/README.md
  packages/react-flicking/README.md
  packages/vue-flicking/README.md
Labels: :bookmark:3.x, :memo: Docs
