Repository naver/egjs-flicking, pull requests merged in 2022-06, with the labels that each got.

#686 refactor: add union type to ViewportSlot
  packages/react-flicking/src/react-flicking/ViewportSlot.tsx
Labels: :bug:Bug, :package:React, :label:Types, :bookmark:4.x

#690 fix: spinning on moving to adjacent panel & restoring
  src/control/SnapControl.ts
  test/manual/js/index.js
  test/unit/control/SnapControl.spec.ts
Labels: :bug:Bug, :bookmark:4.x

#692 feat: add useFractionalSize
  docs/src/pages/Options.mdx
  src/Flicking.ts
  src/core/Viewport.ts
  src/core/panel/Panel.ts
  src/utils.ts
  test/unit/core/Viewport.spec.ts
  test/unit/utils.spec.ts
Labels: :sparkles:Feature, :bookmark:4.x
